networks:
  open-mfa:
    name: open-mfa
    ipam:
      config:
        - subnet: 172.19.0.0/24

services:
  open-mfa:
    image: rodzera/open-mfa:latest
    container_name: open-mfa
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      _SECRET_KEY: ${_SECRET_KEY}
      _ADMIN_USER: ${_ADMIN_USER}
      _ADMIN_PASS: ${_ADMIN_PASS}
      _REDIS_HOST: redis
      _REDIS_PASS: ${_REDIS_PASS}
      HOST: 0.0.0.0
      PORT: 8080
      WORKERS: 4
      THREADS: 64
      WORKER_CONNECTIONS: 8192
      TZ: Etc/Greenwich
    networks:
      open-mfa:
        aliases:
          - open-mfa
        ipv4_address: 172.19.0.2
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    environment:
      _REDIS_PASS: ${_REDIS_PASS}
    command: sh -c 'redis-server --requirepass "$_REDIS_PASS"'
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      open-mfa:
        aliases:
          - redis
        ipv4_address: 172.19.0.3
