openapi: 3.0.3
info:
  title: open-mfa
  description: developed by github.com/rodzera
  version: 1.0.0
servers:
  - url: /api
paths:
  /database:
    get:
      tags:
        - Healthcheck
      summary: Get the status of the database.
      responses:
        200:
          description: Database status response
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime:
                    type: string
                    description: Current timestamp from redis
                    example: "2024-11-01 03:36:58"
                  status:
                    type: string
                    description: Status of the database, either 'up' or 'down'
                    example: "up"
                  version:
                    type: string
                    description: Current redis version
                    example: "7.4.1"
        500:
          description: Database connection error
  /server:
    get:
      tags:
        - Healthcheck
      summary: Get the status of the server.
      responses:
        200:
          description: Server status response
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime:
                    type: string
                    description: Current timestamp from Flask server
                    example: "2024-11-01 03:36:58"
                  status:
                    type: string
                    description: Status of the server, always 'up'
                    example: "up"
                  version:
                    type: string
                    description: Current version of the application
                    example: "1.0.0"
  /otp:
    get:
      tags:
        - OTP
      summary: Generate and verify a One-Time Password (OTP).
      parameters:
        - name: otp
          in: query
          required: false
          description: The OTP to verify (optional).
          schema:
            type: string
      responses:
        200:
          description: OTP generated or verified successfully
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      otp:
                        type: string
                        description: Server side OTP, generated if no OTP is provided for verification
                        example: "123456"
                  - type: object
                    properties:
                      status:
                        type: boolean
                        description: Verification result if an OTP was provided
                        example: true
        400:
          description: Missing OTP in the verification request
        409:
          description: OTP not created or not available for verification
